namespace: mattermost

stack:
  defines: process-group
  balancers:
    app-balancer:
      type: http
      port: 8065
      instances:
          - mattermost/mattermost
  runnable-list:
    - mattermost/database
    - mattermost/mattermost
  variables:
    defines: variables
    db-path:
      type: string
      value: <- `${monk-volume-path}/postgresql/data`
    TZ:
      env: TZ
      type: string
      value: "UTC"
    MM_SQLSETTINGS_DRIVERNAME:
      env: MM_SQLSETTINGS_DRIVERNAME
      type: string
      value: "postgres"
    MM_BLEVESETTINGS_INDEXDIR:
      env: MM_BLEVESETTINGS_INDEXDIR
      type: string
      value: "/mattermost/bleve-indexes"
    MM_SERVICESETTINGS_SITEURL:
      env: MM_SERVICESETTINGS_SITEURL
      type: string
      value: "https://mm.example.com"
    MM_SQLSETTINGS_DATASOURCE:
      env: MM_SQLSETTINGS_DATASOURCE
      type: string
      value: <- `postgres://${postgres-user}:${postgres-password}@${db-host}:5432/${postgres-db}?sslmode=disable&connect_timeout=10`
    postgres-user:
      type: string
      value: "mmuser"
    postgres-password:
      type: string
      value: "mmuser_password"
    postgres-db:
      type: string
      value: "mattermost"
    volume-data:
      type: string
      value: "/volumes/app/"    
    MATTERMOST_CONFIG_PATH:
      type: string
      value: "/volumes/app/mattermost/config"
    MATTERMOST_DATA_PATH:
      type: string
      value: "/volumes/app/mattermost/data"
    MATTERMOST_LOGS_PATH:
      type: string
      value: "/volumes/app/mattermost/logs"
    MATTERMOST_PLUGINS_PATH:
      type: string
      value: "/volumes/app/mattermost/plugins"
    MATTERMOST_CLIENT_PLUGINS_PATH:
      type: string
      value: "/volumes/app/mattermost/client/plugins"
    MATTERMOST_BLEVE_INDEXES_PATH:
      type: string
      value: "/volumes/app/mattermost/bleve-indexes"
    MATTERMOST_IMAGE_TAG:
      type: string
      value: "6.3"
    db-host:
      type: string
      value: <- get-hostname("mattermost/database", "postgres")           