namespace: mattermost

stack:
  defines: process-group
  balancers:
    app-balancer:
      type: http
      port: 80
      instances:
          - mattermost/nginx
  runnable-list:
    - mattermost/database
    - mattermost/mattermost
    - mattermost/nginx    
  variables:
    defines: variables
    db-user:
      type: string
      value: "mmuser"
    db-password:
      type: string
      value: "mmuser_password"   
    db-name:
      type: string
      value: "mattermost"
    listen-port:
      type: int
      value: 8080
    proxy-target-port:
      type: int
      value: 8065
    server-name:
      type: string
      value: "www.example.com"         
    TZ:
      env: TZ
      type: string
      value: "UTC"
    MM_SQLSETTINGS_DRIVERNAME:
      env: MM_SQLSETTINGS_DRIVERNAME
      type: string
      value: "postgres"
    MM_BLEVESETTINGS_INDEXDIR:
      env: MM_BLEVESETTINGS_INDEXDIR
      type: string
      value: "/mattermost/bleve-indexes"
    MM_SERVICESETTINGS_SITEURL:
      env: MM_SERVICESETTINGS_SITEURL
      type: string
      value: "https://mm.example.com"
    MATTERMOST_CONFIG_PATH:
      type: string
      value: "mattermost/config"
    MATTERMOST_DATA_PATH:
      type: string
      value: "mattermost/data"
    MATTERMOST_LOGS_PATH:
      type: string
      value: "mattermost/logs"
    MATTERMOST_PLUGINS_PATH:
      type: string
      value: "mattermost/plugins"
    MATTERMOST_CLIENT_PLUGINS_PATH:
      type: string
      value: "mattermost/client/plugins"
    MATTERMOST_BLEVE_INDEXES_PATH:
      type: string
      value: "mattermost/bleve-indexes"
    MATTERMOST_IMAGE_TAG:
      type: string
      value: "6.3"