namespace: mattermost

stack:
  defines: process-group
  runnable-list:
    - mattermost-enterprise/database
    - mattermost-enterprise/mattermost
    - mattermost-enterprise/nginx
  variables:
    defines: variables
    db-user:
      type: string
      value: "mattermost"
    db-password:
      type: string
      value: "mattermost_password"   
    db-name:
      type: string
      value: "mattermost"
    listen-port:
      type: int
      value: 8080
    server-name:
      type: string
      value: "monk-mattermost-enterprise.com"         
    TZ:
      env: TZ
      type: string
      value: "UTC"
    MM_SERVICESETTINGS_SITEURL:
      env: MM_SERVICESETTINGS_SITEURL
      type: string
      value: "https://mm.example.com"
    MATTERMOST_IMAGE_TAG:
      type: string
      value: "6.3"
    nginx-image-tag: 
       type: string
       value: "latest"